export const mySkills = [
  { title: "C#", icon: "csharp" },
  { title: ".NET Core", icon: "dotnet" },
  { title: "Microsoft Azure", icon: "azure" },
  { title: "TypeScript", icon: "typescript" },
  { title: "React.js", icon: "react" },
  { title: "SQL Server", icon: "database" },
  { title: "T-SQL", icon: "database" },
  { title: "Azure DevOps", icon: "devops" },
  { title: "YAML Pipelines", icon: "yaml" },
  { title: "Power Automate", icon: "automation" },
  { title: "Power Apps", icon: "powerapp" },
  { title: "Entity Framework", icon: "database" },
  { title: "MongoDB", icon: "mongodb" },
  { title: "Docker", icon: "docker" },
  { title: "Blazor", icon: "dotnet" },
  { title: "Git", icon: "git" },
  { title: "Power Fx", icon: "code" },
  { title: "SSO", icon: "code" },
  { title: "OAuth 2.0", icon: "code" },
  { title: "OpenID Connect (OIDC)", icon: "code" },
  { title: "JWT", icon: "code" },
  { title: "REST APIs", icon: "code" },
  { title: "Microservices", icon: "code" },
  { title: "Azure Functions", icon: "azure" },
  { title: "Azure API Management", icon: "azure" },
  { title: "Identity and Access Management (IAM)", icon: "code" },
  { title: "Kubernetes", icon: "devops" },
];